var Modes = [];
Modes.init = function() {
    Lang[lang][15];
    Modes = [{
        name: Lang[lang][3],
        fullName: Lang[lang][3] + " " + Lang[lang][29],
        tag: "classic",
        levels: {}
    }, {
        name: Lang[lang][4],
        fullName: Lang[lang][4] + " " + Lang[lang][29],
        tag: "arcade",
        levels: {}
    }, {
        name: Lang[lang][5],
        fullName: Lang[lang][5] + " " + Lang[lang][29],
        tag: "dzen",
        levels: {}
    }, {
        name: Lang[lang][6],
        fullName: Lang[lang][6] + " " + Lang[lang][29],
        tag: "run",
        levels: {}
    }, {
        name: Lang[lang][7],
        fullName: Lang[lang][7] + " " + Lang[lang][29],
        tag: "trial",
        levels: {}
    }, {
        name: Lang[lang][8],
        fullName: Lang[lang][8] + " " + Lang[lang][29],
        tag: "arcade+",
        levels: {}
    }, {
        name: Lang[lang][9],
        fullName: Lang[lang][9] + " " + Lang[lang][29],
        tag: "arcade+",
        levels: {}
    }], Modes[0].levels[25] = 25, Modes[0].levels[50] = 50, Modes[0].levels[Lang[lang][15]] = 75, Modes[1].levels[Lang[lang][16]] = 6, Modes[1].levels[Lang[lang][17]] = 9, Modes[1].levels[Lang[lang][18]] = -6, Modes[2].levels["15''"] = 15e3, Modes[2].levels["30''"] = 3e4, Modes[2].levels[Lang[lang][15]] = 45e3, Modes[3].levels[Lang[lang][16]] = 6, Modes[3].levels[Lang[lang][18]] = -6, Modes[3].levels[Lang[lang][15]] = 8, Modes[4].levels["8''"] = 8e3, Modes[4].levels["10''"] = 1e4, Modes[4].levels["12''"] = 12e3, Modes[5].levels[Lang[lang][19]] = "Bomb", Modes[5].levels[Lang[lang][20]] = "Double", Modes[5].levels["5x5"] = 5, Modes[6].levels[Lang[lang][21]] = "Lighting", Modes[6].levels[Lang[lang][22]] = "Bi", Modes[6].levels["6x6"] = 6
};
var Songs = ["HKKKHLJKHKNNMLKJKLHKKKHLJKHKMOMKILMKNMLIIJKLLNMLIIJKLLHKKKHLJKHKMOMKILMKILMKK", "LHIJKLHHMKLMNOHHKLKJIJKJIHGHIJHILHIJKLHHMKLMNOHHKLKJIJKJIHIJIHGHQOPQOPLMNLOMNOLKJKIIJKLMNONMNIKLLHGHMHGHIHGHIEFGHIJKJIJLHGH", "LOOOOPOPQPOOQSTTSQQOPOPQPOMMLOLOOOOPOPQPOOQSTTSQQOPOPQPOMMLOLOOOOPOPQPOOQSTTSQQOPOPQPOMMLOLOOOOPOPQPOOQSTTSQQOPOPQPOMMLO", "OOSSTTSRRQQPPOSSRRQQPSSRRQQPOOSSTTSRRQQPPOOOSSTTSRRQQPPOSSRRQQPSSRRQQPOOSSTTSRRQQPPO", "HHHHGHIHIIIIHIJIHJMLJJMLJJJJJJMLKJIJKHIIIIIILKJIHLNMLKJNPONMLJJJJMLKJIJKHIIIIIILKJIHFGHIIJHHHHGHIHIIIIHIJIHJMLJJMLJOOOONNNNMNJIHGFMLJMMLJMJIHGHHLJMMLJMJIHGFLM", "LLQOPONOMKKNMLLLQONOPQRMMNONMNOLLMLMLRQPQOMNNMNMNOPRQPOSQSRQPRQONOPLJLJMLMLOLOLRPRPSSOPQRQPSQOPPQLMNOOPQRSQSQSSQSQRQPSRPRPRRQPRQSOLOQONOPQRMNMLMNPONO", "KKKKKKKKOPQRSTUTXWUTSSSSTUVWXYXTZYXWXVTZYXYZWVZXWVUVWXUSTVUVWXSSOTSRQPQRSRTOQRUTOTSSRRQPOO", "JIHKJIJIHGHIJIHKJIJIHGHIJKLMMMMMNNNNMMMMNNNNMNMNMNMNMNNNNOOOONNNNOOOONONONONONMNOPONMNOPQRQPQMNOPONMNOPQRQPQQRSTSRQPONMLKJIHGFGHIHGFGHIJKJIJMNOPONMNOPQRQPQTSRQPONMLKJIHGEFFFFF", "EIIJIHHJKMOMMLLMGGMLHHJJIJIJIJIEIIJIHHJKMOMMLLMGGMLHHJJIJIJIHQOMLLIJKJIHQOMLKLMNPOOQOMLLIJKJIHQOMLKLMNOLNLOLNLOLNLOLNLOOOOEOPRQPSSSTQRPPPRQPOHNMLKJIOOPRQPSSSTQRPPPRQPOSPQO", "ELELLKJIHGFIFIEFGHIJELELLKJIHGGJGJGIJKGHHKKJIIHCCIHCCIHDDKKJIIHCCCDEFGHIJKMKKKJIIHCCIHCCIHDDKKJIIHCEEFGHJEHHOHOOONMLJILILHIJKLMHOHOOOMMLJILILJHIJJK", "QPQPQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMNOPQLRQPKQPOJPONNJQQQQPQ§PQNPOMHJMNJLNOJQPQPQNPOMHJMNJONMORQQPPRTSRQPONMMLMNOPPQRMOPNOPQSPNOPQSPNQQQQQP", "JJKLLKJIHHIJJIIJJKLLKJIHHIJIHHIIJHIJKJHIJKJIHIEJJKLLKJIHHIJIHHJJKLLKJIHHIJJIIJJKLLKJIHHIJIHHIIJHIJKJHIJKJIHIEJJKLLKJIHHIJIHH", "IHDKKIHDKKIHDKBKAJJIHAJJIHAJJIHAJBJDKKIHMKKIHMKKIHMHOHPJJIHPJJIHPJJIHPHMHKMKKLMOOKLMOOKLMOOOPOMLKIIMLKIIMLKIIHIK", "QSQPQPQQPMOQPPOMOPQSPQTSSPOPOMOPQSPQTSSQPQPOSTQMQPPOQSVSTTSQQSSQSTVWVSQPSQQQSVSTVWVSQSVTQPQSXWVV", "QPOPQSSSSTSTUVVVVVVUTSTTSSSQPOQRQPPQPPQPPPOOOOPOOTUVVVVVVUTSSSQPOVVVVWWWVWXXWVVVVVWWSSXWVVVVVWWWWVUVTTUTUVVVWVWXXWXV", "LOQSONQSSTUVTSQPOOOQPOOOPQPOMPQPLOQSONQSSTUVTSPOOOQPOOOPQPMNOPOQSQPOSNMNMNMLQSQPOSNMNOOOPQPLOQSONQSSTUVTSQPOOOQPOOOPQPMNOPO", "LJIHIGFENMNLMKJLIJLIJKJIHLGIFHEFHECEFHIFHELOMLJLIIJGFEFHICHFEFHEJLGIFHECECEFGIFEFHILJIJIHFECHFHFECEFHEJLIJIHGFE", "MOMJMJHJHFCFIGHGHGGHIGHFMOMJMJHJHFHGHHGHMHHGJKJJKJOJJIFHFEFIFEFKJIJHGFHGHGFMOMJMJHJHFCFIGHGHGGHIGHFMOMJMJHJHFHGHHGHMHHGJKJJKJOJJIFHFEFIFEFKJIJHGFHGHGF"];