function GetPlatformAction(a, b) {
    return a ? Lang[b][0] : Lang[b][1]
}
var Lang = {
    en: ["Click", "Touch", "to start", "Classic", "Arcade", "Lite", "Rush", "Relay", "Arcade+", "Arcade 2.0", "Sound", "piano", "typewriter", "Off", "More Games", "PRO", "Normal", "Faster", "Reverse", "Bomb", "Double", "Lighing", "Bilayer", "Time Out", "Score", "Best", "Again", "Main Menu", "Failed", "Mode"],
    ru: ["Нажмите", "Коснитесь", "для начала", "Классик", "Аркада", "Дзэн", "Погоня", "Эстафета", "Аркада+", "Аркада 2.0", "Звук", "фортепьяно", "пишущая машинка", "Выкл", "Больше игр", "ПРО", "Нормально", "Быстрее", "Реверс", "Мина", "Двойник", "Молния", "Двойной слой", "Время вышло", "Количество очков", "Лучший", "Снова", "Главное Меню", "Не удалось", "Режим"],
    de: ["Klicken", "Berühren", "zum Start", "Klassisch", "Arcade", "Lite", "Rush", "Relay", "Arcade +", "Arcade 2.0", "Töne", "Klavier", "Schreibmaschine", "Aus", "Mehr Spiele", "PRO", "Normal", "Schneller", "Rückwärts", "Bombe", "Doppelt", "Blitz", "Doppelschicht", "Auszeit", "Punktzahl", "Highscore", "Wiederholung", "Hauptmenü", "Verloren", "Modus"],
    es: ["Haz clic", "Pulsa", "para iniciar", "Clásico", "Arcade", "Lite", "Rápido", "Relajante", "Arcade+", "Arcade 2.0", "Sonido", "piano", "máquina de escribir", "Off", "Más juegos", "PRO", "Normal", "Más rápido", "Inverso", "Bomba", "Doble", "Relámpago", "Bicapa", "Se acabó el tiempo", "Puntuación", "Mejores", "Jugar otra vez", "Menú principal", "Fallaste", "Modo"],
    fr: ["Cliquer", "Toucher", "pour démarrer", "Classique", "Arcade", "Lite", "Rush", "Relais", "Arcade+", "Arcade 2.0", "Son", "Piano", "Machine à écrire", "Off", "Plus de Jeux", "PRO", "Normal", "Plus rapide", "Reverse", "Bombe", "Double", "Éclairage", "Bicouche", "Temps écoulé", "Score", "Le meilleur", "De nouveau", "Menu principal", "Échec", "Mode"],
    it: ["Clicca", "Tocca", "per iniziare", "Modalità classic", "Modalità arcade", "Modalità Lite", "Modalità rush", "Modalità relay", "Arcade+", "Arcade 2.0", "Audio", "Pianoforte", "Macchina da scrivere", "Off", "Altri giochi", "PRO", "Normale", "Più veloce", "Modalità reverse", "Bomba", "Doppio", "Fulmine", "Doppio strato", "Tempo scaduto", "Punteggio", "\n Miglior \n punteggio", "Riprova", "Menu principale", "Hai perso", "Modalità"],
    pt: ["Clicar", "Tocar", "para iniciar", "Clássico", "Arcada", "Lite", "Rápido", "Estafeta", "Arcada+", "Arcada 2.0", "Som", "Piano", "Máquina de escrever", "Desligar", "Mais jogos", "PRO", "Normal", "Mais rápido", "Invertido", "Bomba", "Duplo", "Relâmpago", "Camada dupla", "Tempo esgotado", "Pontuação", "Melhor pontuação", "Novamente", "Menu principal", "Falhaste", "Modo"],
    tk: ["tıklayın", "dokunun", "Başlatmak için", "Klasik", "Oyun", "Lite", "Hamle", "Aktar", "Oyun+", "Oyun 2.0", "Ses", "Piyano", "Daktilo", "Kapalı", "Daha Fazla Oyun", "PRO", "Normal", "Daha Hızlı", "Geri", "Bomba", "İki Kat", "Şimşek", "İki Tabaka", "Süre Bitti", "Skor", "En İyi Puan", "Tekrar", "Ana Menü", "Başarısız", "Mod"],
    ja: ["クリックして", "タッチして", "（スタート）", "クラシック", "アーケード", "ゼン", "ラッシュ", "リレー", "アーケード＋", "アーケード 2.0", "サウンド", "ピアノ", "タイプライター", "オフ", "次のゲーム", "プロ", "ノーマル", "ファースト", "リバース", "ボム", "ダブル", "ライトニング", "バイレイヤー", "タイムアウト", "今回のスコア", "ベスト", "再開", "メインメニュー", "失敗", "モード"]
};