//Games List :
//============

var new_list = [
	{name: 'Zumbla Deluxe', 	icon: 'icons/a_zumbla.png', 	link: './games/zumbla_deluxe/index.html' },
	{name: 'Snake vs Blocks', 	icon: 'icons/a_snake.png', 		link: './games/snake_vs_blocks/index.html' },
	{name: 'Bubble Frozen', 	icon: 'icons/a_frozen.png', 	link: './games/bubble_frozen/index.html' },
	{name: 'Tennis', 			icon: 'icons/tennis.jpg', 		link: './games/tennis/index.html' },
	{name: 'Dentist', 			icon: 'icons/dentist.jpg', 		link: './games/dentist/index.html' },
	{name: 'Fruits Match3', 	icon: 'icons/fruits_match3.jpg', link: './games/fruits_match3/index.html' },
	{name: 'Princess', 			icon: 'icons/princess.jpg', 	link: './games/princess/index.html' },
	
];

var games_list =  [
	{name: 'Fruits_cutter', 	icon: 'icons/fruits_cutter.png', link: './games/fruits_cutter/index.html' },
	{name: 'Escape Runner', 	icon: 'icons/escape_aztec.jpg', link: './games/escape_aztec/index.html' },
	{name: 'Checkers Deluxe', 	icon: 'icons/checkers_deluxe.png', link: './games/checkers_deluxe/index.html' },
	{name: 'Maze 400', 			icon: 'icons/maze400.png', 		link: './games/maze400/index.html' },
	{name: 'Dentist', 			icon: 'icons/dentist.jpg', 		link: './games/dentist/index.html' },
	{name: 'Puzzle Block Ancient', icon: 'icons/puzzleblock_ancient.jpg', 	link: './games/puzzleblock_ancient/index.html' },
	{name: 'Neon Hockey', 		icon: 'icons/neon_hockey.jpg', 	link: './games/neon_hockey/index.html' },
	{name: 'Classic Car Racing', icon: 'icons/classic_car.jpg', link: './games/classic_car/index.html' },
	{name: 'Cookie Crush', 		icon: 'icons/cookie_crush.jpg', link: './games/cookie_crush/index.html' },
	{name: 'Little Hand Doctor', icon: 'icons/hand_doctor.jpg', link: './games/hand_doctor/index.html' },
	{name: 'Soccer Skills', 	icon: 'icons/soccer_skills.jpg', link: './games/soccer_skills/index.html' },
	{name: 'Piano', 			icon: 'icons/piano.jpg', 		link: './games/piano/index.html' },
	{name: 'Line Follower', 	icon: 'icons/line_follower.jpg', link: './games/line_follower/index.html' },
	{name: 'Ladybug Dentist', 	icon: 'icons/ladybug_dentist.jpg', link: './games/ladybug_dentist/index.html' },
	{name: 'Guitar Hero', 		icon: 'icons/guitar_hero.jpg', 	link: './games/guitar_hero/index.html' },
	{name: 'Bounce Ball', 		icon: 'icons/bounce_ball.jpg', 	link: './games/bounce_ball/index.html' },
	{name: 'Pongoal', 			icon: 'icons/pongoal.jpg', 		link: './games/pongoal/index.html' },
	{name: 'Touch Balance', 	icon: 'icons/touch_balance.jpg', link: './games/touchbalance/index.html' },
	{name: 'Farm Match', 		icon: 'icons/farm_match.jpg', 	link: './games/farm_match/index.html' },
	{name: 'Doctor Acorn', 		icon: 'icons/doctor_acorn.jpg', link: './games/doctor_acorn/index.html' },
	{name: 'Boun2y', 			icon: 'icons/boun2y.jpg', 		link: './games/boun2y/index.html' },
	{name: 'Boat Rush', 		icon: 'icons/boat_rush.jpg', 	link: './games/boat_rush/index.html' },
	{name: 'Halloween Match', 	icon: 'icons/haloween_match.jpg', link: './games/haloween_match/index.html' },
	{name: 'Hexagon Color', 	icon: 'icons/hexagon.jpg', 		link: './games/hexagone/index.html' },
	{name: 'Bowling Classic', 	icon: 'icons/bowling.jpg', 		link: './games/bowling/index.html' },
	{name: 'Wash Pets', 		icon: 'icons/wash_pets.jpg', 	link: './games/wash_pets/index.html' },
	{name: 'Climbing UP', 		icon: 'icons/climbing_up.jpg', 	link: './games/climbing_up/index.html' },
	{name: 'Knife Try', 		icon: 'icons/knife_try.jpg', 	link: './games/knife_try/index.html' },
	{name: 'Flow Free', 		icon: 'icons/flow_free.jpg', 	link: './games/flow_free/index.html' },
	{name: 'Box Stacker', 		icon: 'icons/boxstacker.jpg', 	link: './games/boxstacker_v2/index.html' },
	{name: 'Flip Bottle', 		icon: 'icons/flip_bottle.jpg', 	link: './games/flip_bottle/index.html' },
	{name: 'Core Ball', 		icon: 'icons/core_ball.jpg', 	link: './games/core_ball/index.html' },
	{name: 'Ice Trouble', 		icon: 'icons/ice_trouble.jpg', 	link: './games/ice_trouble/index.html' },
	{name: 'Tic Tac Toe', 		icon: 'icons/tic_tac_toe.jpg', 	link: './games/tic_tac_toe/index.html' },
	{name: 'Baby Care', 		icon: 'icons/baby_care.jpg', 	link: './games/baby_care/index.html' },
	{name: 'Dot Snap', 			icon: 'icons/dot_snap.jpg', 	link: './games/dot_snap/index.html' },
	{name: 'Dunk Balls', 		icon: 'icons/dunk_balls.jpg', 	link: './games/dunk_balls/index.html' },
	{name: 'Sea Match3', 		icon: 'icons/sea_match3.jpg', 	link: './games/sea_match3/index.html' },
	{name: 'Minion Haircut', 	icon: 'icons/minion_haircut.jpg', link: './games/minion_haircut/index.html' },
	{name: 'Scaled', 			icon: 'icons/scaled.jpg', 		link: './games/scaled/index.html' },
	{name: 'Foot Surgery', 		icon: 'icons/foot_surgery.jpg', link: './games/foot_surgery/index.html' },
	{name: 'Crazy Colors', 		icon: 'icons/crazy_colors.jpg', link: './games/crazy_colors/index.html' },
	{name: 'Funny Match3', 		icon: 'icons/funny_match3.jpg', link: './games/funny_match3/index.html' },
	{name: 'White Ball', 		icon: 'icons/white_ball.jpg', 	link: './games/white_ball/index.html' },
	{name: 'Mad Taxi', 			icon: 'icons/mad_taxi.jpg', 	link: './games/mad_taxi/index.html' },
	{name: 'Drop Me', 			icon: 'icons/drop_me.jpg', 		link: './games/drop_me/index.html' },
	{name: 'Happy Chicken Jump', icon: 'icons/happy_jump.jpg', 	link: './games/happy_jump/index.html' },
	{name: 'Gerdooter', 		icon: 'icons/gerdooter.jpg', 	link: './games/gerdooter/index.html' },
	{name: 'Hop Hop Hop', 		icon: 'icons/hop.jpg', 			link: './games/hop_hop_hop/index.html' },
	{name: 'Ice Maker', 		icon: 'icons/ice_maker.jpg', 	link: './games/ice_maker/index.html' },
	{name: 'Cubies', 			icon: 'icons/cubies.jpg', 		link: './games/cubies/index.html' },
];
